feign:
  hystrix:
    enabled: true

logging:
  level:
    ca:
      purpleowl:
        examples:
          boot2:
            feign:
              service:
                omega:
                  client: DEBUG
#    ca.purpleowl.examples.boot2.feign.service.omega.client.ServiceBetaClient: DEBUG

management:
  server:
    port: 8081

server:
  port: 8080

service:
  alpha:
    url: http://localhost:8420/api
  beta:
    url: http://localhost:8710/api

spring:
  application:
    name: Service Omega
  jersey:
    application-path: api
