logging:
  level:
    ca:
      purpleowl:
        examples:
          boot2:
            feign:
              service:
                omega:
                  client: DEBUG

management:
  server:
    port: 8081

server:
  port: 8080

service:
  alpha:
    url: http://localhost:8420/api
    auth:
      username: example
      password: elpmaxe
  beta:
    url: http://localhost:8710/api

spring:
  application:
    name: Service Omega
  jersey:
    application-path: api

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 10
      ringBufferSizeInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 60s
      failureRateThreshold: 25
  instance:
    serviceAlpha:
      baseConfig: default
      ringBufferSizeInClosedState: 4

