management:
  server:
    port: 8421

server:
  port: 8420
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:alpha-db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop